### ISSUE TITLE
In consistent interval of time

### ISSUE THREAD

**Issue by zenggyu** [tidyverts/tsibble#134]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

When using integers to define the index of a `tsibble`, the unit of the interval can be inconsistent. For example (notice that the interval of the first `tsibble` is `[1]`, while the interval of the second is `[1Y]`):

```r
library(tsibble)

tsibble(year = 1581:1582, index = year)
#> # A tsibble: 2 x 1 [1]
#>    year
#>   <int>
#> 1  1581
#> 2  1582

tsibble(year = 1582:1583, index = year)
#> # A tsibble: 2 x 1 [1Y]
#>    year
#>   <int>
#> 1  1582
#> 2  1583
```

Is there a good reason for this behaviour? IMO there should be an explicit way of specifying years as the index (just like `yearquarter` for quarterly data, `yearmonth` for monthly data, etc.); alternatively, as long as the index only consists of integers, the unit of the interval should be year.

**Comment by earowang** [comment]
To recognise as "year", the index containing numbers needs to fall into the range [1582-2499](https://github.com/tidyverts/tsibble/blob/cb07859587632b202259d1b2305e6eec592b50a8/R/interval.R#L132), otherwise as units. The year of 1582 is when the Gregorian calendar started.

`yearquarter` and `yearmonth` are created because they are more appropriate representations (subclassing of dates). But `year` is `integer`, not a subclassing of integers, that would make the class redundant.

With respect to modelling, there's no difference between 1 year and 1 unit.
