### ISSUE TITLE
index() behavior

### ISSUE THREAD

**Issue by SteffenMoritz** [tidyverts/tsibble#153]
Recently I stumbled about some things with the index() function.
Thought I'd post them here - but might very well be these are deliberate design choices.

The first thing is, I somehow expected tsibble::index() to return the actual indices - as I am somehow used to this from other time series packages like zoo and xts. 
(left me even more wondering, since there is also index_var() )

The second thing is that I had some namespace problems / conflicts, since the function it is  tsibble::index() and not tsibble::index.tsibble(). So tsibble basically overtakes index() completely if loaded last - instead of just in cases when needed for tsibbles.

Besides this: Keep up the good work, I really like the package :)

**Comment by earowang** [comment]
Thanks Steffen. Tsibble's design tries to be consistent with the tidyverse operations and outputs.  Similar to `dplyr::groups()` and `dplyr::group_vars()`, `index()` gives a symbol and `index_var()` returns the string for index variable. To pull the index values, I'd recommend the following, which also demonstrates the difference between `index()` and `index_var()`.

``` r
library(tsibble)
head(pedestrian %>% dplyr::pull(!!index(pedestrian)))
#> [1] "2015-01-01 00:00:00 AEDT" "2015-01-01 01:00:00 AEDT"
#> [3] "2015-01-01 02:00:00 AEDT" "2015-01-01 03:00:00 AEDT"
#> [5] "2015-01-01 04:00:00 AEDT" "2015-01-01 05:00:00 AEDT"
head(pedestrian[[index_var(pedestrian)]])
#> [1] "2015-01-01 00:00:00 AEDT" "2015-01-01 01:00:00 AEDT"
#> [3] "2015-01-01 02:00:00 AEDT" "2015-01-01 03:00:00 AEDT"
#> [5] "2015-01-01 04:00:00 AEDT" "2015-01-01 05:00:00 AEDT"
```

Since tsibble is a melted data format with multiple series, the `index` coupled with `key` appear more useful. The standalone `index` gives many duplicated values, unlike `zoo` & `xts`.

Regarding namespace conflicts, I'd suggest to the [conflicted](https://github.com/r-lib/conflicted) package to resolve the issue for interactive use.
<sup>Created on 2019-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SteffenMoritz** [comment]
Hi Earo,
thanks a lot for your fast and extensive explanation. 
Now hearing your reasoning, that sounds like a very good design choice :-)
Also thx for the link to the conflicted package - didn't know this one yet.
