### ISSUE TITLE
grouped_ts[0, ] aborts R session

### ISSUE THREAD

**Issue by earowang** [tidyverts/tsibble#194]
```r
library(tsibble)
grped_ped <- pedestrian %>% dplyr::group_by(Sensor)
grped_ped[0, ]
```

**Comment by stuvet** [comment]
Successful workaround for #208 (& this?):

Ungroup before as_tsibble then regroup.

**Comment by earowang** [comment]
Oh, #208 is resolved, so I closed it (not bc of duplicate). You can `fill_gaps()` a grouped tsibble. This issue is much harder, and haven't locate the root yet.

**Comment by davidtedfordholt** [comment]
The R session is aborting during the `build_tsibble()` call at the end of the `[.tbl_ts` definition. The reason it's aborting has to do with the use of `res` in the call.

If I add a `return(res)` to the `[.tbl_ts` function, just after it's created (and then store that into `[.grouped_ts`), I get the following object:

```
# A tibble: 0 x 5
# Groups:   Sensor [0]
# … with 5 variables: Sensor <chr>, Date_Time <dttm>, Date <date>, Time <int>, Count <int>
```

If I add `print(str(res))`, I get this from the call as a `grouped_ts`:
```
tsibble [0 × 5] (S3: grouped_ts/grouped_df/tbl_ts/tbl_df/tbl/data.frame)
 $ Sensor   : chr(0) 
 $ Date_Time: 'POSIXct' num(0) 
 - attr(*, "tzone")= chr "Australia/Melbourne"
 $ Date     : 'Date' num(0) 
 $ Time     : int(0) 
 $ Count    : int(0) 
 - attr(*, "key")= tibble [4 × 2] (S3: tbl_df/tbl/data.frame)
  ..$ Sensor: chr [1:4] "Birrarung Marr" "Bourke Street Mall (North)" "QV Market-Elizabeth St (West)" "Southern Cross Station"
  ..$ .rows : list<int> [1:4] 
  .. ..$ : int [1:14566] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..$ : int [1:16414] 14567 14568 14569 14570 14571 14572 14573 14574 14575 14576 ...
  .. ..$ : int [1:17518] 30981 30982 30983 30984 30985 30986 30987 30988 30989 30990 ...
  .. ..$ : int [1:17539] 48499 48500 48501 48502 48503 48504 48505 48506 48507 48508 ...
  .. ..@ ptype: int(0) 
  ..- attr(*, ".drop")= logi TRUE
 - attr(*, "index")= chr "Date_Time"
  ..- attr(*, "ordered")= logi TRUE
 - attr(*, "index2")= chr "Date_Time"
 - attr(*, "interval")= interval [1:1] 1h
  ..@ .regular: logi TRUE
 - attr(*, "groups")= tibble [4 × 2] (S3: tbl_df/tbl/data.frame)
  ..$ Sensor: chr [1:4] "Birrarung Marr" "Bourke Street Mall (North)" "QV Market-Elizabeth St (West)" "Southern Cross Station"
  ..$ .rows : list<int> [1:4] 
  .. ..$ : int [1:14566] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..$ : int [1:16414] 14567 14568 14569 14570 14571 14572 14573 14574 14575 14576 ...
  .. ..$ : int [1:17518] 30981 30982 30983 30984 30985 30986 30987 30988 30989 30990 ...
  .. ..$ : int [1:17539] 48499 48500 48501 48502 48503 48504 48505 48506 48507 48508 ...
  .. ..@ ptype: int(0) 
  ..- attr(*, ".drop")= logi TRUE
NULL
```
and this from the `NextMethod` call to the same function as a `grouped_df` (note that this happens because `[.grouped_df` makes a `NextMethod` call back to `[.tbl_ts`, which then makes a `NextMethod` call to `[.tbl_df`, which doesn't include a `NextMethod` call):
```
tibble [0 × 5] (S3: grouped_df/tbl_df/tbl/data.frame)
 $ Sensor   : chr(0) 
 $ Date_Time: 'POSIXct' num(0) 
 - attr(*, "tzone")= chr ""
 $ Date     : 'Date' num(0) 
 $ Time     : int(0) 
 $ Count    : int(0) 
 - attr(*, "key")= tibble [0 × 2] (S3: tbl_df/tbl/data.frame)
  ..$ Sensor: chr(0) 
  ..$ .rows : list<int> [1:0] 
 list()
  .. ..@ ptype: int(0) 
  ..- attr(*, ".drop")= logi TRUE
 - attr(*, "index")= chr "Date_Time"
  ..- attr(*, "ordered")= logi TRUE
 - attr(*, "index2")= chr "Date_Time"
 - attr(*, "interval")= interval [1:1] ?
  ..@ .regular: logi TRUE
 - attr(*, "groups")= tibble [0 × 2] (S3: tbl_df/tbl/data.frame)
  ..$ Sensor: chr(0) 
  ..$ .rows : list<int> [1:0] 
 list()
  .. ..@ ptype: int(0) 
  ..- attr(*, ".drop")= logi TRUE
NULL
```
The structure of the object I get from adding `return(res)` is:
```
tsibble [0 × 5] (S3: tbl_ts/tbl_df/tbl/data.frame)
 $ Sensor   : chr(0) 
 $ Date_Time: 'POSIXct' num(0) 
 - attr(*, "tzone")= chr ""
 $ Date     : 'Date' num(0) 
 $ Time     : int(0) 
 $ Count    : int(0) 
 - attr(*, "key")= tibble [0 × 2] (S3: tbl_df/tbl/data.frame)
  ..$ Sensor: chr(0) 
  ..$ .rows : list<int> [1:0] 
 list()
  .. ..@ ptype: int(0) 
  ..- attr(*, ".drop")= logi TRUE
 - attr(*, "index")= chr "Date_Time"
  ..- attr(*, "ordered")= logi TRUE
 - attr(*, "index2")= chr "Date_Time"
 - attr(*, "interval")= interval [1:1] ?
  ..@ .regular: logi TRUE
```
Obviously, the object we receive from the `return(res)` is coming from the inner call, as a `tbl_ts`, not from the outer, as a `grouped_ts`. That return from the inner call is an object that can be printed and can be used in `build_tsibble` to create a valid `tsibble` object. The object we receive from the outer call, though we can print its structure, is where the issue exists.

In that `[.grouped_df` expects its `NextMethod` call to be `[.tbl`, it seems like you'll either need to change the order of the classes of a `grouped_df` (which seems tricky, given the whole "you can't just change the class manually" thing), or you'll need to write a `[.grouped_ts` function that calls `[.tbl_ts` explicitly, using the same arguments as the `[.grouped_ts` call.

I am 100% NOT certain that this is the right fix, but I am 92% certain that the creation of the `res` object in the recursive `NextMethod` calls is the source of the issue.

**Comment by earowang** [comment]
It's a very corner case. I don't understand why `[.grouped_ts` works for all integers except for `0`.

**Comment by davidtedfordholt** [comment]
It's super edge-y, but I am using it as an exercise in bug tracing and learning about Classes and whatnot. What I don't know is how the environments are working during the nested `NextMethod` calls, and what about the `return(res)` and `print(str(red))` makes the object safe in a way that `print(res)` and `build_tsibble(res, ...)` do not.

I'll probably keep digging later today, just to keep learning!
