### ISSUE TITLE
loading package causes a lot functions to fail

### ISSUE THREAD

**Issue by stahengik** [tidyverts/tsibble#283]
Loading tsibble package is causing a lot of functions to fail with error "Error in make_ansi_style(x[["color"]]) : Unknown style specification: br_magenta"
eg:
![image](https://user-images.githubusercontent.com/10901832/183830526-cd7ec8f4-af5d-4c1b-9444-5a4e9ba1a8de.png)

This does not only happen with this skim command but even select and mutate in dplyr
```r

```

**Comment by stahengik** [comment]
Sorry, I am not sure anymore if this issue is due to tsibble package on its own. 
It happened after installing "clock" package which had me update a bunch of other packages.

I am able to run things fine on another machine. so something went wrong with R / Rstudio on my machine.

**Comment by JPScaccia** [comment]
Ditto here. Whatever this error is, it's even overriding other errors on my box, so this is the only thing that is being displayed. I thought it had to do with my Rstudio them (tomorrow night).  It's even killing a lot of the basic ggplot2 themes, like _scale_fill_brewer_

**Comment by earowang** [comment]
Have you resolved this issue? It's not the issue arisen from {tsibble}. This error is triggered from the {cli} package, probably because one of the packages you installed happened to reply on the development version of {cli}.

**Comment by livelikegourav** [comment]
Locally this issue is not reproducible. Facing this error quite frequently on the server. 
Error Message : 

Error in make_ansi_style(x[["color"]]) :
Unknown style specification: br_magenta
Calls: <Anonymous> ... structure -> theme_create -> lapply -> FUN -> make_ansi_style.

Can someone help in resolving this issue?

Solutions tried : 

Installing cli did not help.

@earowang - will you be able to help here?
