### ISSUE TITLE
Preserves index gives different behaviour than documentation

### ISSUE THREAD

**Issue by 0Matt** [tidyverts/tsibble#45]
---

Select help refers to dplyr help. dpylr help says "select() keeps only the variables you mention".
In this case, select keeps the mentioned variable plus the index. Might be worth calling this out.

```r
library(bomrang)
library(tidyverse)
library(tsibble)
library(lubridate)

gove_airport_rainfall <- "014508" %>% get_historical(type = "rain")
# Remove limited recording periods
gove_airport_rainfall <- gove_airport_rainfall %>%
  filter(Year > 1986)

gove_airport_rainfall <- gove_airport_rainfall %>%  mutate(date = paste(gove_airport_rainfall$Year, gove_airport_rainfall$Month, gove_airport_rainfall$Day, sep='-')) %>%
  mutate(date = as.Date(date))

gove_airport_rainfall <- gove_airport_rainfall %>% mutate(Year = year(date))

# now there is a date column, make tsibble
gove_airport_rainfall <- gove_airport_rainfall %>% as_tsibble()

gove_airport_rainfall %>% select(Rainfall)
```

**Comment by alexhallam** [comment]
+1

I noticed this also, when doing `summarise` after a `select`. I was surprised to see the index still there. If I remember correctly I ended up converting from a `tsibble` to a `tibble` then doing a `summarise`.

**Comment by earowang** [comment]
Thx for pointing it out. I've updated the documentation in the dev version. Previously, it threw out an error saying "the index cannot be dropped". Since `v0.4.0`, it started to preserve the index automatically assuming users expect to keep the temporal context. All the column-wise verbs including `mutate()`, `transmute()`, `select()` and `summarise()`, have `.drop = FALSE` as additional argument for users consciously switching from `tsibble` to `tibble`.
